ctags=`brew --prefix`/bin/ctags
PATH=/`brew --prefix`/bin/python:$PATH
PATH=/`brew --prefix`/bin/ruby:$PATH
#alias vim='/usr/local/Cellar/macvim/8.0-124/MacVim.app/Contents/MacOS/Vim'
#alias vi='/usr/local/Cellar/macvim/8.0-124/MacVim.app/Contents/MacOS/Vim'
alias vim=Gvim
alias vi=Gvim
alias gdb='sudo ggdb'
alias chrome="/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --kiosk"
alias norminette="~/Documents/42/norminette42/bin/norminette"
alias zshconfig="~/.zshrc"
alias ohmyzsh="~/.oh-my-zsh"
#alias ctags="`brew --prefix`/bin/ctags"
alias 42projects="cd ~/Documents/42"
alias soularchive="cd ~/Documents/of_v0.9.3_osx_release/apps/SoulArchive"
alias ofxaddons="cd ~/Documents/of_v0.9.3_osx_release/addons"

export PATH=~/bin:$PATH
export PATH=/opt/local/bin:/opt/local/sbin:$PATH
